import { Header } from '@/components/Header';
import {Footer} from '@/components/Footer';

import './globals.css'
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'

const lato = Lato({
   subsets: ['latin'],
   weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'NextJs + Tailwind',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
